### PR TITLE
Confusion about how Node and JS work

### PR DESCRIPTION
**Pull request by joker314**
When you pass a value to a function, the value gets passed, not the condition that created the value. This means that the value is aways the same. Therefore, the condition must be a lambda and not a value.

### CODE REVIEW

**Comment by Firedrake969** [comment]
"all languages"?  JS sometimes passes by reference (it's annoying and you can't control it though).

**Comment by joker314** [comment]
Sorry; tired.

But anyway, in this instance, a lambda should be passed

**Comment by Firedrake969** [comment]
Why?

**Comment by Firedrake969** [comment]
Here's an example.  Run this in your console.
```js
test = [1,2,3]
(function(a){a[0]=5})(test)
console.log(test[0])
```

**Comment by joker314** [comment]
Uncaught type error, it says the first class list is not a function

**Comment by joker314** [comment]
Oh, you missed a semicolon

**Comment by joker314** [comment]
I'll run it with punctuation

**Comment by Firedrake969** [comment]
http://prntscr.com/bev4we

**Comment by joker314** [comment]
to do what?

**Comment by Firedrake969** [comment]
Why do you need to have a repeatUntil function is a while loop does essentially the exact same thing?

**Comment by joker314** [comment]
Yes, `while(!(condition))` is basically it

**Comment by bjskistad** [comment]
The `repeatUntil` function's first parameter (`happens`) is a boolean, not a function, so no extra parentheses are required. I'm gonna close.

**Comment by joker314** [comment]
So why did you react with a thumbs down if the argument passed will be a boolean? And why should this be closed, since @bjskistad wants this feature to be implemented? I will contact @bjskistad

**Comment by joker314** [comment]
Oh sorry, I didn't see that @bjskistad was the one that made the close. I'll contact them anyway

**Comment by bjskistad** [comment]
I have no idea what this pr is trying to accomplish.

**Comment by Firedrake969** [comment]
@joker314 I would retract it but, honestly, where is the function even needed?

**Comment by bjskistad** [comment]
I ran it with the PR merged...
```
while (!happens()) {
            ^

TypeError: happens is not a function
    at Object.exports.repeatUntil (/home/ubuntu/workspace/scratch-js.js:26:13)
    at Object.<anonymous> (/home/ubuntu/workspace/test.js:7:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.runMain [as _onTimeout] (module.js:441:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by joker314** [comment]
Did you pass a function in?

**Comment by Firedrake969** [comment]
No, because `happens is not a function` :P

**Comment by Firedrake969** [comment]
Did you see my above comments?
Why is a `repeatUntil` even needed?  It's literally `while` with an inverted condition.

**Comment by joker314** [comment]
I agree, but it is beside the point. `happens` is a function when you merge it. It is the only way I can think of that is most convenient to the developer that really doesn't need this :P

**Comment by joker314** [comment]
Why is it saying that this was "closed"? Who closed it?

**Comment by bjskistad** [comment]
We are trying to implement Scratch-like functions.

**Comment by joker314** [comment]
But even in Scratch the old way wouldn't work, give me a sec..

**Comment by Firedrake969** [comment]
It's not beside the point - why bother working on an unneeded feature?  @bjskistad What may be a better idea is to give documentation of how to use other Scratch features in JS (or Python, C++, etc) if they're essentially the same.

@joker314 http://prntscr.com/beve1l

**Comment by joker314** [comment]
Thanks, I just noticed that

**Comment by bjskistad** [comment]
@joker314 This module doesn't have to be used just for Scratchers. We already have time and date APIs, so it could be used for that.

**Comment by joker314** [comment]
True. So shall we forget the reeatUntil (don't close yet plz)

**Comment by bjskistad** [comment]
Sure.

**Comment by joker314** [comment]
We can implement other scratch-like feautres though

**Comment by Firedrake969** [comment]
Why was this reopened?  lol
Closing it and removing the unneeded functionality would be the best course of action, imo

**Comment by bjskistad** [comment]
Exactly, and this is essentially [Slither](https://github.com/PySlither/Slither), accept is made in JavaScript therefore we don't need PyGame.

**Comment by Firedrake969** [comment]
Slither seems more like a way to use sprites in Python (as opposed to trying to recreate stuff like `repeat (x)`) - if you want to make something like that, you're probably better of making a canvas library

**Comment by joker314** [comment]
True. Just wait before closing, I'm making a scratchblocks thing to show pass by reference in case people still don't quite understand

**Comment by Firedrake969** [comment]
Either close it or merge it.  Which one?  Does that mean there's a possibility of being merged, since it's still open?

**Comment by bjskistad** [comment]
K. Yes, slither is majorly about sprites. I'm saying that this essentially another Scratch module, except in JS.

**Comment by Firedrake969** [comment]
What do you mean by "Scratch module"?  What sort of functionality will it provide?

**Comment by bjskistad** [comment]
It's just Scratch functions in Node. It also has a bunch of other helpful APIs.

**Comment by joker314** [comment]
[Click here for those that don't quite understand why this PR was made](https://scratchblocks.github.io/#define%20wait_until%20%3Ccondition%3E%0Arepeat%20until%20%3Ccondition%3E%0Aend%0Await_until%20%3Ctouching%20%5B%2300ff00%5D%3E%3A%3Adefine%20%2F%2FThis%20will%20not%20work%2C%20because%20when%20you%20do%20this%0A%2F%2FScratch%20replaces%20it%20like%20so%0Await_until%20%3Cfalse%3A%3Aoperators%3E%0A%2F%2FSo%20the%20code%20just%20thinks...%0A%0Arepeat%20until%20%3Cfalse%3A%3Aoperators%3E%0Aend%0A%0A%2F%2FSo%20that%20is%20annoying%2C%20and%20is%20our%20point%20of%20discussion.%0A%0A%2F%2FSince%20it%20would%20be%20better%20to%20pass%20a%20lambda%20value%20that%20would%20change%20its...%0A%2F%2FRetur%20value%20each%20time%20our%20script%20calls%20it%20to%20check%20its%20condition.)

**Comment by Firedrake969** [comment]
@bjskistad So there's some advantage to wrapping a `while` loop in a function rather than just saying how you can use `repeat until` in JS?

**Comment by joker314** [comment]
Ok, a Scratch Module, sounds fun.
Do we really need `repeatUntil` as you can see from that demo, you have to pass a lambda, and unfortunately that just takes up way more characters than an `!` that means not

**Comment by joker314** [comment]
ninja'd if I understand correctly (?)

**Comment by bjskistad** [comment]
Great, now we have conflicts.

**Comment by joker314** [comment]
Why?

**Comment by bjskistad** [comment]
A recent commit.

**Comment by Firedrake969** [comment]
Because he made the same changes that the pull request did instead of merging it.

**Comment by bjskistad** [comment]
NOT TRUE. I deleted the function completely.

**Comment by Firedrake969** [comment]
It's true.
https://github.com/chikadi/scratch-js/commit/1f594d41e36bf8fc6ad090378233484f5fb4d932

**Comment by bjskistad** [comment]
That's what we agreed on. No need to make any changes to a function if it doesn't exist, so I'm gonna close.

**Comment by bjskistad** [comment]
WHAT??? oh, lol.

**Comment by joker314** [comment]
Oh well. Shall we close, as I don't see this being used (it having to use 2 lambdas and all)

**Comment by bjskistad** [comment]
I forgot to add my latest changes.

**Comment by joker314** [comment]
kk

**Pull request closed without merging**
