### PR TITLE
Added new blocks.

### PR DESCRIPTION
**Pull request by BKFighter**
!!!!!     Somebody please check to make sure that those functions work.     !!!!!

### CODE REVIEW

**Comment by joker314** [comment]
I don't see why it wouldn't, looks great! I'm not sure if the round, ceiling and floor should  be separate functions? I dunno

**Comment by bjskistad** [comment]
Looks good to me! I'll test em. +1

**Comment by bjskistad** [comment]
They work, they just need to have some syntax stuff added. :)

**Comment by BKFighter** [comment]
Glad they work! (I wrote those blind. Didn't have time to try and test.) @bjkistad whats buoy mean by 'syntax stuff'?

**Pull request merged**
